name: Release with Maven

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 21

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email '16764085+RoiArthurB@users.noreply.github.com'

    - name: Build with Maven
      run: |
        mvn deploy -Prelease-composite -Dgithub-update-repo=https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/project-SIMPLE/gaml.extension.unity
      working-directory: eu.project-simple.parent

